add image.flavor to allow choosing between alpine, debian and ubuntu
traccar/traccar-helm pull request #20
Opened 2023-02-10 19:42 UTC by tamcore

As https://github.com/traccar/traccar-docker and https://hub.docker.com/r/traccar/traccar show 3 different image flavors (`alpine`, `debian` and `ubuntu`), it would be nice to be able to configure just the flavor, without having to worry about manually updating the full tag, when there's a new traccar release.

Default value
```
$ helm template .  | grep 'image: traccar'
          image: traccar/traccar:4.13
```

Custom tag
```
$ helm template . --set image.tag=v1234 | grep 'image: traccar'
          image: traccar/traccar:v1234
```

(so no breaking of existing behaviour)

Setting the flavor
```
$ helm template . --set image.flavor=alpine | grep 'image: traccar'
          image: traccar/traccar:4.13-alpine
```

Setting the flavor and a custom version through `image.tag`
```
$ helm template . --set image.flavor=alpine,image.tag=v123 | grep 'image: traccar'
          image: traccar/traccar:v123-alpine
```

2023-02-10 20:01 UTC, tananaev commented
@kondas can you please review this PR.

2023-02-10 22:23 UTC, kondas commented
@tamcore Thanks for the contribution, super clean solution. Could You please amend some instructions to the readme also? This is a very useful feature.

2023-02-11 10:24 UTC, tamcore commented
@kondas done so :)

2023-02-11 10:29 UTC, kondas requested changes
Almost perfect :)

2023-02-11 10:29 UTC, kondas commented on charts/traccar/Chart.yaml
> +version: 1.3.1
I suggest a minor version bump instead bugfix

2023-02-11 10:31 UTC, tamcore commented on charts/traccar/Chart.yaml
> +version: 1.3.1
Fixed :)

2023-02-11 10:44 UTC, kondas approved these changes
Thanks, awesome!

2023-02-11 15:15 UTC, merged